transform_data:
  outputs:
    dev:
      dbname: "{{ env_var('DESTINATION_DB_NAME', '') }}"
      host: "{{ env_var('DESTINATION_DB_HOST', '') }}"
      pass: "{{ env_var('DESTINATION_DB_PASSWORD', '') }}"
      port: "{{ env_var('DESTINATION_DB_PORT', '') | as_number }}"
      schema: "{{ env_var('DESTINATION_DB_SCHEMA', '') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('DESTINATION_DB_USERNAME', '') }}"
  target: dev
